//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("LangLearnModel", "FK_Spanish_ToEnglish", "English", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(LangLearnModel.English), "Spanish", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LangLearnModel.Spanish), true)]

#endregion

namespace LangLearnModel
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class LangLearnEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new LangLearnEntities object using the connection string found in the 'LangLearnEntities' section of the application configuration file.
        /// </summary>
        public LangLearnEntities() : base("name=LangLearnEntities", "LangLearnEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new LangLearnEntities object.
        /// </summary>
        public LangLearnEntities(string connectionString) : base(connectionString, "LangLearnEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new LangLearnEntities object.
        /// </summary>
        public LangLearnEntities(EntityConnection connection) : base(connection, "LangLearnEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<English> Englishes
        {
            get
            {
                if ((_Englishes == null))
                {
                    _Englishes = base.CreateObjectSet<English>("Englishes");
                }
                return _Englishes;
            }
        }
        private ObjectSet<English> _Englishes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Spanish> Spanishes
        {
            get
            {
                if ((_Spanishes == null))
                {
                    _Spanishes = base.CreateObjectSet<Spanish>("Spanishes");
                }
                return _Spanishes;
            }
        }
        private ObjectSet<Spanish> _Spanishes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<User> Users
        {
            get
            {
                if ((_Users == null))
                {
                    _Users = base.CreateObjectSet<User>("Users");
                }
                return _Users;
            }
        }
        private ObjectSet<User> _Users;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Englishes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEnglishes(English english)
        {
            base.AddObject("Englishes", english);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Spanishes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSpanishes(Spanish spanish)
        {
            base.AddObject("Spanishes", spanish);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsers(User user)
        {
            base.AddObject("Users", user);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LangLearnModel", Name="English")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class English : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new English object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="word">Initial value of the Word property.</param>
        public static English CreateEnglish(global::System.Int32 id, global::System.String word)
        {
            English english = new English();
            english.Id = id;
            english.Word = word;
            return english;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Word
        {
            get
            {
                return _Word;
            }
            set
            {
                OnWordChanging(value);
                ReportPropertyChanging("Word");
                _Word = StructuralObject.SetValidValue(value, false, "Word");
                ReportPropertyChanged("Word");
                OnWordChanged();
            }
        }
        private global::System.String _Word;
        partial void OnWordChanging(global::System.String value);
        partial void OnWordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Picture
        {
            get
            {
                return _Picture;
            }
            set
            {
                OnPictureChanging(value);
                ReportPropertyChanging("Picture");
                _Picture = StructuralObject.SetValidValue(value, true, "Picture");
                ReportPropertyChanged("Picture");
                OnPictureChanged();
            }
        }
        private global::System.String _Picture;
        partial void OnPictureChanging(global::System.String value);
        partial void OnPictureChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PartOfSpeech
        {
            get
            {
                return _PartOfSpeech;
            }
            set
            {
                OnPartOfSpeechChanging(value);
                ReportPropertyChanging("PartOfSpeech");
                _PartOfSpeech = StructuralObject.SetValidValue(value, true, "PartOfSpeech");
                ReportPropertyChanged("PartOfSpeech");
                OnPartOfSpeechChanged();
            }
        }
        private global::System.String _PartOfSpeech;
        partial void OnPartOfSpeechChanging(global::System.String value);
        partial void OnPartOfSpeechChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LangLearnModel", "FK_Spanish_ToEnglish", "Spanish")]
        public EntityCollection<Spanish> SpanishWords
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Spanish>("LangLearnModel.FK_Spanish_ToEnglish", "Spanish");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Spanish>("LangLearnModel.FK_Spanish_ToEnglish", "Spanish", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LangLearnModel", Name="Spanish")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Spanish : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Spanish object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="word">Initial value of the Word property.</param>
        /// <param name="englishId">Initial value of the EnglishId property.</param>
        public static Spanish CreateSpanish(global::System.Int32 id, global::System.String word, global::System.Int32 englishId)
        {
            Spanish spanish = new Spanish();
            spanish.Id = id;
            spanish.Word = word;
            spanish.EnglishId = englishId;
            return spanish;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Word
        {
            get
            {
                return _Word;
            }
            set
            {
                OnWordChanging(value);
                ReportPropertyChanging("Word");
                _Word = StructuralObject.SetValidValue(value, false, "Word");
                ReportPropertyChanged("Word");
                OnWordChanged();
            }
        }
        private global::System.String _Word;
        partial void OnWordChanging(global::System.String value);
        partial void OnWordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 EnglishId
        {
            get
            {
                return _EnglishId;
            }
            set
            {
                OnEnglishIdChanging(value);
                ReportPropertyChanging("EnglishId");
                _EnglishId = StructuralObject.SetValidValue(value, "EnglishId");
                ReportPropertyChanged("EnglishId");
                OnEnglishIdChanged();
            }
        }
        private global::System.Int32 _EnglishId;
        partial void OnEnglishIdChanging(global::System.Int32 value);
        partial void OnEnglishIdChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LangLearnModel", "FK_Spanish_ToEnglish", "English")]
        public English EnglishWords
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<English>("LangLearnModel.FK_Spanish_ToEnglish", "English").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<English>("LangLearnModel.FK_Spanish_ToEnglish", "English").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<English> EnglishWordsReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<English>("LangLearnModel.FK_Spanish_ToEnglish", "English");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<English>("LangLearnModel.FK_Spanish_ToEnglish", "English", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LangLearnModel", Name="User")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class User : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new User object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static User CreateUser(global::System.Int32 id, global::System.String name)
        {
            User user = new User();
            user.Id = id;
            user.Name = name;
            return user;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false, "Name");
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> QuizScore
        {
            get
            {
                return _QuizScore;
            }
            set
            {
                OnQuizScoreChanging(value);
                ReportPropertyChanging("QuizScore");
                _QuizScore = StructuralObject.SetValidValue(value, "QuizScore");
                ReportPropertyChanged("QuizScore");
                OnQuizScoreChanged();
            }
        }
        private Nullable<global::System.Int32> _QuizScore;
        partial void OnQuizScoreChanging(Nullable<global::System.Int32> value);
        partial void OnQuizScoreChanged();

        #endregion

    }

    #endregion

}
