//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class LangLearnEntities : DbContext
{
    public LangLearnEntities()
        : base("name=LangLearnEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<English> Englishes { get; set; }
    public virtual DbSet<Spanish> Spanishes { get; set; }
    public virtual DbSet<User> Users { get; set; }
}
