//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class English
{
    public English()
    {
        this.Spanishes = new HashSet<Spanish>();
    }

    public int Id { get; set; }
    public string Word { get; set; }
    public string Picture { get; set; }
    public string PartOfSpeech { get; set; }

    public virtual ICollection<Spanish> Spanishes { get; set; }
}

public partial class Spanish
{
    public int Id { get; set; }
    public string Word { get; set; }
    public int EnglishId { get; set; }

    public virtual English English { get; set; }
}

public partial class User
{
    public int Id { get; set; }
    public string Name { get; set; }
    public Nullable<int> QuizScore { get; set; }
}
